### ISSUE TITLE
Latex comment support

### ISSUE THREAD

**Issue by raulmrebane** [Abercus/LaTeXEE#61]
ignoring formulas and other things in comments.

**Comment by Abercus** [comment]
Comments in formulas are also to be considered. There are infinite syntax combinations to describe comments in LaTeX documents..

**Comment by Abercus** [comment]
Adding \n to comment breaks it and changing grammar to ignore more than one \r\n breaks it..

**Comment by Abercus** [comment]
No need to handle infinite amount of syntax combinations. As long as normal \begin{comment} \end{comment} block comments and %-line comments works then it is good to go.

**Comment by Abercus** [comment]
Can't seem to fix % line comments.
